codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 85%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto
    changes:
      default:
        target: 80%
        threshold: 1%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "tests/"
  - "docs/"
  - "examples/"
  - "scripts/"
  - "**/__pycache__/"
  - "**/test_*.py"
  - "**/*_test.py"
  - "**/conftest.py"
  - "setup.py"
  - "versioneer.py"
  - "_version.py"

flags:
  unittests:
    paths:
      - src/cryptex/
    carryforward: false
  integration:
    paths:
      - tests/integration/
    carryforward: false
  security:
    paths:
      - tests/security/
    carryforward: false
  performance:
    paths:
      - tests/performance/
    carryforward: false