# Advanced Cryptex Configuration for Examples
# This configuration demonstrates all available features and options

[secrets]
# Comprehensive secret patterns for production use

[[secrets.patterns]]
name = "openai_api_key"
pattern = "sk-[a-zA-Z0-9]{48}"
template = "{RESOLVE:OPENAI_API_KEY:{hash}}"
description = "OpenAI API key (GPT-3/4, DALL-E, etc.)"

[[secrets.patterns]]
name = "anthropic_api_key"
pattern = "sk-ant-[a-zA-Z0-9]{95}"
template = "{RESOLVE:ANTHROPIC_API_KEY:{hash}}"
description = "Anthropic API key (Claude)"

[[secrets.patterns]]
name = "google_api_key"
pattern = "AIza[0-9A-Za-z-_]{35}"
template = "{RESOLVE:GOOGLE_API_KEY:{hash}}"
description = "Google API key"

[[secrets.patterns]]
name = "aws_access_key"
pattern = "AKIA[0-9A-Z]{16}"
template = "{RESOLVE:AWS_ACCESS_KEY:{hash}}"
description = "AWS access key"

[[secrets.patterns]]
name = "aws_secret_key"
pattern = "[A-Za-z0-9/+=]{40}"
template = "{RESOLVE:AWS_SECRET_KEY:{hash}}"
description = "AWS secret key"

[[secrets.patterns]]
name = "jwt_token"
pattern = "eyJ[a-zA-Z0-9_-]+\\.eyJ[a-zA-Z0-9_-]+\\.[a-zA-Z0-9_-]+"
template = "{RESOLVE:JWT_TOKEN:{hash}}"
description = "JWT tokens"

[[secrets.patterns]]
name = "database_url_postgresql"
pattern = "postgresql://[^\\s]+"
template = "{RESOLVE:DATABASE_URL:{hash}}"
description = "PostgreSQL connection string"

[[secrets.patterns]]
name = "database_url_mysql"
pattern = "mysql://[^\\s]+"
template = "{RESOLVE:DATABASE_URL:{hash}}"
description = "MySQL connection string"

[[secrets.patterns]]
name = "redis_url"
pattern = "redis://[^\\s]+"
template = "{RESOLVE:REDIS_URL:{hash}}"
description = "Redis connection string"

[[secrets.patterns]]
name = "mongodb_url"
pattern = "mongodb://[^\\s]+"
template = "{RESOLVE:MONGODB_URL:{hash}}"
description = "MongoDB connection string"

[[secrets.patterns]]
name = "email_address"
pattern = "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
template = "{RESOLVE:EMAIL:{hash}}"
description = "Email addresses"

[[secrets.patterns]]
name = "ip_address"
pattern = "\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b"
template = "{RESOLVE:IP_ADDRESS:{hash}}"
description = "IP addresses"

[[secrets.patterns]]
name = "file_path_unix"
pattern = "/[^\\s]+"
template = "/{USER_HOME}/.../{filename}"
description = "Unix file paths"

[[secrets.patterns]]
name = "file_path_windows"
pattern = "[A-Za-z]:\\\\[^\\s]+"
template = "C:\\\\Users\\\\{USER}\\\\...\\\\{filename}"
description = "Windows file paths"

[[secrets.patterns]]
name = "credit_card"
pattern = "\\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3[0-9]{13}|6(?:011|5[0-9]{2})[0-9]{12})\\b"
template = "{RESOLVE:CREDIT_CARD:{hash}}"
description = "Credit card numbers"

[[secrets.patterns]]
name = "social_security"
pattern = "\\b[0-9]{3}-[0-9]{2}-[0-9]{4}\\b"
template = "{RESOLVE:SSN:{hash}}"
description = "Social security numbers"

[[secrets.patterns]]
name = "phone_number"
pattern = "\\b(?:\\+?1[-.]?)?\\(?[0-9]{3}\\)?[-.]?[0-9]{3}[-.]?[0-9]{4}\\b"
template = "{RESOLVE:PHONE:{hash}}"
description = "Phone numbers"

[[secrets.patterns]]
name = "generic_secret"
pattern = "[a-zA-Z0-9]{32,}"
template = "{RESOLVE:SECRET:{hash}}"
description = "Generic long strings (likely secrets)"

[security]
# Advanced security settings
enforcement_mode = "strict"  # Options: "strict", "permissive", "audit"
block_exposure = true
max_placeholder_age = 1800  # 30 minutes
audit_logging = true
auto_detect_secrets = true
enable_secret_validation = true
max_secret_length = 2048
min_secret_length = 8

[performance]
# Advanced performance settings
cache_size = 10000
sanitization_timeout_ms = 500
resolution_timeout_ms = 1000
batch_size = 500
enable_background_cleanup = true
cleanup_interval_seconds = 300  # 5 minutes
max_concurrent_operations = 100
enable_compression = true
cache_ttl_seconds = 3600  # 1 hour

[middleware]
# Advanced middleware settings
auto_protect_endpoints = true
auto_protect_tools = true
sanitize_request_headers = true
sanitize_response_headers = true
sanitize_request_body = true
sanitize_response_body = true
sanitize_query_params = true
sanitize_form_data = true
max_request_size = 52428800   # 50MB
max_response_size = 52428800  # 50MB
request_timeout_seconds = 30
response_timeout_seconds = 30
enable_request_logging = true
enable_response_logging = true
enable_metrics_collection = true

[monitoring]
# Monitoring and observability settings
enable_performance_monitoring = true
enable_security_monitoring = true
collect_detailed_metrics = true
export_prometheus_metrics = false
metrics_port = 8080
health_check_endpoint = "/health"
metrics_endpoint = "/metrics"

[logging]
# Logging configuration
level = "INFO"  # Options: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
format = "json"  # Options: "json", "text"
include_context = true
include_performance_metrics = true
max_log_file_size = "100MB"
max_log_files = 10
log_rotation = "daily"

[custom]
# Custom application-specific settings
application_name = "Cryptex Examples"
environment = "development"
version = "1.0.0"
enable_debug_mode = true
custom_placeholder_prefix = "RESOLVE"
custom_user_placeholder = "USER_HOME"