blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://anthemflynn.github.io/cryptex-ai/
    about: Read the official Cryptex-AI documentation
  - name: 💬 Discussions
    url: https://github.com/AnthemFlynn/cryptex-ai/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Advisories
    url: https://github.com/AnthemFlynn/cryptex-ai/security/advisories
    about: Report security vulnerabilities privately