name: Feature Request
description: Suggest a new feature for Codename
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out this form as completely as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read the documentation and this feature is not already available
          required: true
        - label: This feature aligns with Codename's purpose (AI/LLM secrets isolation)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        I'm always frustrated when...
        Currently, it's difficult to...
        Users need to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: |
        I would like to see...
        The feature should...
        This could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        Alternative 1: ...
        Alternative 2: ...
        Current workaround: ...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would be helpful"
        - "High - Important for my use case"
        - "Critical - Blocking my use case"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - "Core API"
        - "Security Enhancement"
        - "Performance Improvement"
        - "Developer Experience"
        - "Integration (FastMCP, FastAPI, etc.)"
        - "Configuration"
        - "Documentation"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        I want to use this feature to...
        In my application, I need to...
        This would help me...
    validations:
      required: true

  - type: textarea
    id: api_design
    attributes:
      label: API Design (Optional)
      description: If you have ideas about how this feature should work, provide example code
      render: python
      placeholder: |
        # Example of how this feature might work
        import codename
        
        # Your proposed API here

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I would be willing to submit a pull request for this feature
        - label: I would be willing to help with testing
        - label: I would be willing to help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information...