name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python 3.11
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --dev

    - name: Lint with ruff
      run: |
        uv run ruff check src/ tests/ --output-format=github

    - name: Format check with ruff
      run: |
        uv run ruff format --check src/ tests/

    - name: Type check with mypy
      run: |
        uv run mypy src/ --show-error-codes

    - name: Check import sorting
      run: |
        uv run ruff check --select I src/ tests/

    - name: Security lint with bandit
      run: |
        uv run bandit -r src/ -ll -f txt

    - name: Check for security issues in dependencies
      run: |
        uv run safety check --short-report

  docs-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check markdown files
      uses: DavidAnson/markdownlint-cli2-action@v18
      with:
        globs: '**/*.md'

    - name: Check links in markdown
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/link-check-config.json'
        folder-path: '.'
        max-depth: 2