name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
      
    - name: Install dependencies
      run: |
        uv sync --extra dev
        uv pip install build twine
      
    - name: Run tests
      run: uv run pytest tests/ -v
      
    - name: Run security checks
      run: |
        uv run bandit -r src/
        uv run safety check
        
    - name: Build package
      run: uv run python -m build
      
    - name: Check package
      run: uv run twine check dist/*
      
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        attestations: true
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
        generate_release_notes: true
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}