name: Update Dependencies

on:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6 AM
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          
      - name: Create virtual environment
        run: uv venv
        
      - name: Install dependencies
        run: uv pip install -e ".[dev]"
        
      - name: Update dependencies
        run: |
          uv pip list --outdated --format=json > outdated.json
          echo "Outdated packages:"
          cat outdated.json
          
      - name: Security check
        run: uv run safety check --json --output security-report.json || true
        
      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security-report.json
          
      - name: Create issue for outdated packages
        if: ${{ hashFiles('outdated.json') != '' }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const outdated = JSON.parse(fs.readFileSync('outdated.json', 'utf8'));
            
            if (outdated.length > 0) {
              const body = `## Outdated Dependencies Report
              
              The following packages have updates available:
              
              ${outdated.map(pkg => `- **${pkg.name}**: ${pkg.version} → ${pkg.latest_version}`).join('\n')}
              
              Please review and update as appropriate.
              
              _This issue was created automatically by the Update Dependencies workflow._`;
              
              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Outdated Dependencies Report',
                body: body,
                labels: ['dependencies', 'maintenance']
              });
            }